### ISSUE TITLE
При считывании в пустой аккумулятор из ВУ флаг нуля не сбрасывается

### ISSUE THREAD

**Issue by BakasaRus** [JustAGod1/bevm#5]
Дал студенту задание посчитать сумму вводимых по прерыванию с устройства чисел до тех пор, пока не введётся 0, и вместе с ним наткнулись на то, что после очистки аккумулятора и считывания числа из устройства флаг нуля не сбрасывается, что приводит к неправильному выполнению

Минимальный пример:

| Адрес | Мнемоника |
|-------|-----------|
| 010   | `CLA`       |
| 011   | `IN 001`    |
| 012   | `BEQ 014`   |
| 013   | `MOV 020`   |
| 014   | `HLT`       |

Программа не запишет число в ячейку и сразу завершится

**Comment by JustAGod1** [comment]
Исправил и сделал релиз. Спасибо за ишью.

Дело было в том что флаг нуля в микропроцессоре обновляется операционной командой, но при обработке IN таковая не вызывается. Допустим это еще одна фишка, которую неявно должен делать модуль взаимодейятвия с ВУ.
