### ISSUE TITLE
Различие ячеек в памяти МПУ и методичке

### ISSUE THREAD

**Issue by FeToR1** [JustAGod1/bevm#8]
В ЭВМ

![image](https://user-images.githubusercontent.com/74432501/235713131-559cd549-b537-485a-8408-d32887bcef57.png)

![image](https://user-images.githubusercontent.com/74432501/235713906-06cc0462-5adf-4a6f-a8e6-ceb4ccb4155c.png)

В методичке

![image](https://user-images.githubusercontent.com/74432501/235713343-decd6641-f239-46ac-bbd8-5e9c5da777ee.png)

Так и задумано?

**Comment by JustAGod1** [comment]
Скорее всего так и задумано. В методичке много раз находил баги и код мк
взят из книги. Если не совпадает то это конечно повод задуматься.

**Comment by FeToR1** [comment]
Не подскажите, какая книжка?

**Comment by JustAGod1** [comment]
она есть в рид ми но вот:
https://books.ifmo.ru/file/pdf/761.pdf
